### ISSUE TITLE
Query about MMedAgent Checkpoints

### ISSUE THREAD

**Issue by Znull-1220** [Wangyixinxin/MMedAgent#1]
Hi @Wangyixinxin Thanks a lot for sharing the code of ur excellent work!

I am reproducing the code and trying to deploy the model, and I downloaded MMedAgent Checkpoint checkpoints (lora) from [here](https://huggingface.co/andy0207/mmedagent/tree/main) which you have provided. But I didn't find the doc to explain the the structure and the difference of the checkpoints in `andy0207/mmedagent/tree/main/final_model_lora/pt_files`. could you add a description about the checkpoints..?

Furthermore, I'd like to know if it is feasible to deploy the checkpoint of MMedAgent following the steps in **Build Web UI and Server**?

Many Thanks!

**Comment by Wangyixinxin** [comment]
Hi! Thanks for your interest in our work and sorry for the unclear instructions! We updated the [base model download](https://github.com/Wangyixinxin/MMedAgent?tab=readme-ov-file#base-model-download) and [inference](https://github.com/Wangyixinxin/MMedAgent?tab=readme-ov-file#apply-lora-if-you-enable-lora-during-training) instruction. A short explanation here, we couldn't directly publish the LLaVA-Med 7b weights due to license issue, so here we provide codes for you to apply the delta to llama7b to obtain LLaVA-Med 7b weights. When you do inference, set --model-path as `./checkpoints/final_model_lora` which is the folder you downloaded [here](andy0207/mmedagent/tree/main/final_model_lora). The structure of this folder is the output from LLaVA with Lora-enabled.

As for deploying the model, following our WebUI build-up would be a better way. With the current inference codes and our checkpoints, you could build MMedAgent that accurately calls the tools but the real implementations of the tools are not included. You could separately implement the tools you want and then return the output to the agent. We are working on building inference codes that can be deployed and will update later. Currently, you could build on our WebUI to deploy our MMedAgent.

**Comment by Znull-1220** [comment]
Thanks a lot for your prompt respond! I have solved the problem aforementioned yesterday, sorry for the late update. However, when I built on Web UI, I encountered some new problems:

1. Checkpoint of MedSAM: There is no instruction about checkpoint of MedSAM. I noticed you used `medsam_vit_b` in `serve/MedSAM_worker.py` and I downloaded it from [here](https://drive.google.com/drive/folders/1ETWmi4AiniJeWOt6HAsYgTjYv_fkgzoN), but when I executed `python serve/MedSAM_worker.py` to launch tool worker, an error occured, saying the dimensions of the checkpoint tensor don't match the model. Could you plz tell me which checkpoint should I use for MedSAM?

2. The import code of modules in the folder `MMedAgent/serve`, such as https://github.com/Wangyixinxin/MMedAgent/blob/0e1948ffc280584e9f3d937b4c90a4eb43332c5d/serve/grounding_dino_worker.py#L6 is incorrect following your instruction for organizing folder structures, I think it should be `from src.GroundingDINO.groundingdino.util import box_ops`. If it is not clear, I can open a PR for you to check.

**Comment by YuantingPan** [comment]
Hi, thanks for pointing out the issues. We have updated certain codes and readme to fix these.
1. The first problem is because that the MedSAM repo employs vit-h SAM by default, while their released checkpoint uses vit-b. Please refer to [HERE](https://github.com/Wangyixinxin/MMedAgent/tree/main?tab=readme-ov-file#build-web-ui-and-server) for modification.
2. We updated a few codes and pip install instructions for tools, and fixed some package conflicts. We recommend re-creating the environment following the updated readme and try again.

**Comment by Znull-1220** [comment]
Thanks, by the way there is still something wrong with MedSAM... when I test _Grounding + Segmentation Examples_, I encounter this bug:

![KeyError](https://github.com/user-attachments/assets/328290bf-5fd1-459f-a114-c9ae5bde9e3d)

There was no key "boxes" in the ”res“ dict.

**Comment by YuantingPan** [comment]
This is because of a version conflict arises due to tools overwriting dependencies, which leads to communication issue between the tool and gradio webpage. 
To resolve it, please run:
`pip install httpx==0.24.0 supervision==0.10.0`
It has also been updated in readme. Thanks for catching that.

**Comment by Znull-1220** [comment]
@YuantingPan Thanks for your explanation and sooo sorry for disturbing again! I'm trying to reproduce the experiment result in the paper, but when I run `python llava/eval/eval_gpt4o.py`, there is a KeyError here:
https://github.com/Wangyixinxin/MMedAgent/blob/b7382afbce6e043202244459874139d126f2f2c9/llava/eval/eval_gpt4o.py#L111
I changed the key 'prompt' into  'pre_text', such as "Can you create a medical report from this image?". However, gpt-4o can't generate the report. Could you plz tell me that, in the evaluation phase, does gpt-4o infer the case based on the all infos given by the certain tool in your work, or just simple image - question pair. （what does the key 'prompt' refer to?

By the way, I didn't find `/llava/eval/eval_multimodal_chat_gpt_score.py` in the repo. Is the current version behind?
